name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: syncread-linux-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: syncread-windows-x86_64.exe

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Install system dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev libmpv-dev
    
    - name: Install MPV (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        # Download MPV dev libraries for Windows
        curl -L https://sourceforge.net/projects/mpv-player-windows/files/libmpv/mpv-dev-x86_64-20240303-git-2768db8.7z/download -o mpv-dev.7z
        7z x mpv-dev.7z
        echo "MPV_LIB_DIR=${{ github.workspace }}/mpv-dev" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=${{ github.workspace }}/mpv-dev/pkgconfig" >> $GITHUB_ENV
    
    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Prepare artifact
      shell: bash
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          cp target/${{ matrix.target }}/release/syncread.exe ${{ matrix.artifact }}
        else
          cp target/${{ matrix.target }}/release/syncread ${{ matrix.artifact }}
        fi
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: ${{ matrix.artifact }}